apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-kubernetes-docker-react-deployment
  labels:
    app: jenkins-kubernetes-docker-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-kubernetes-docker-react
  template:
    metadata:
      labels:
        app: jenkins-kubernetes-docker-react
    spec:
      containers:
      - name: jenkins-kubernetes-docker-react
        image: saisamarth21/jenkins-kubernetes-docker-react:latest   
        ports:
        - containerPort: 4173
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-kubernetes-docker-react-service
spec:
  type: NodePort
  selector:
    app: jenkins-kubernetes-docker-react
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4173
    nodePort: 30080
